---
kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: default

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: node
  commands:
  - npm install
- name: container
  image: plugins/docker
  settings:
    username: mstephan
    password: wCsPt4zM9NZsk3oAH9iUKwePtzuLaf
    repo: registry.emu10k1.me/kubectl
    registry: registry.emu10k1.me
    tags: latest
